### PR TITLE
Add Tesseract OCR in for powershell script

### PR DESCRIPTION
**Pull request by KrishPatel13**
**What kind of change does this PR introduce?**
BugFix: Tesseract-OCR not found! [on running pytest]

**Summary**
Motivation: #295

**Checklist**
* [x] My code follows the style guidelines of OpenAdapt
* [x] I have performed a self-review of my code
* [x] If applicable, I have added tests to prove my fix is functional/effective
* [x] I have linted my code locally prior to submission
* [x] I have commented my code, particularly in hard-to-understand areas
* [x] I have made corresponding changes to the documentation (e.g. README.md, requirements.txt)
* [x] New and existing unit tests pass locally with my changes

**How can your code be run and tested?**
On Windows: Open powershell" and Run the following command:
`powershell -noexit -ExecutionPolicy Bypass -Command "iwr -UseBasicParsing -Uri 'https://raw.githubusercontent.com/MLDSAI/OpenAdapt/16c18e5c521a9460ef1db812b59978b5098dd25b/install/install_openadapt.ps1' | Invoke-Expression"`

**Other information**

### CODE REVIEW

**Comment by KrishPatel13** [comment]
Demo Test MP4 File on slack:
https://mldsai.slack.com/files/U056HTNBQ5S/F05DEEQD79V/administrator__windows_powershell_2023-06-22_17-13-35.mp4

**Comment by KrishPatel13** [comment]
@abrichr Ready to be merged!

**Comment by KrishPatel13** [comment]
Note: I have not altered any of the Git, VC REDIT and Python Installation in the .ps1 script.

I have just added TesseractOCR functionality

**Review by KrishPatel13 — COMMENTED** [review]
Self-Reviewed!

**Comment by AvidEslami** [comment]
```Powershell
PS D:\MLDSAI\puterbot\puterbot-copy> powershell -noexit -ExecutionPolicy Bypass -Command "iwr -UseBasicParsing -Uri 'https://raw.githubusercontent.com/KrishPatel13/OpenAdapt/feature/install/install/install_openadapt.ps1' | Invoke-Expression"
Downloading Tesseract OCR installer
Installing Tesseract OCR, click 'Yes' if prompted for permission
Exception calling "SetEnvironmentVariable" with "3" argument(s): "Requested registry access is not allowed."
At line:111 char:5
+     [System.Environment]::SetEnvironmentVariable("Path", $env:Path, [ ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : SecurityException

Added Tesseract OCR to PATH
tesseract v5.3.1.20230401
 leptonica-1.83.1
  libgif 5.2.1 : libjpeg 8d (libjpeg-turbo 2.1.4) : libpng 1.6.39 : libtiff 4.5.0 : zlib 1.2.13 : libwebp 1.3.0 : libopenjp2 2.5.0
 Found AVX2
 Found AVX
 Found FMA
 Found SSE4.1
 Found libarchive 3.6.2 zlib/1.2.13 liblzma/5.2.9 bz2lib/1.0.8 liblz4/1.9.4 libzstd/1.5.2
 Found libcurl/8.0.1 Schannel zlib/1.2.13 brotli/1.0.9 zstd/1.5.4 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.3) libssh2/1.10.0
Success: check tesseract version
Success: clone git repo
Downloading python installer
Installing python, click 'Yes' if prompted for permission
Error after installing python. Uninstalling, click 'Yes' if prompted for permission
```

Seems to have downloaded and installed Tesseract OCR correctly, failed on python installation (Perhaps due to existing python version). Repo appeared within the directory, but was deleted afterwards.

**Comment by KrishPatel13** [comment]
@AvidEslami 

Thank you testing!

I am currently looking in the error: The error indicated that it was not able to and the Tesseract in the System Variable. 
But It indeed adde in the User Account Path Variable.

So this might require slight change in the script. :)

**Comment by KrishPatel13** [comment]
@abrichr We will have to edit the command on for installation for the powershell script on the Website:
Reason: As @AvidEslami pointed out the Error, It came due to "editing the Path variable in Non-administrator mode of powershell"

So we need to make sure the whole powershell script runs in Administrator Mode of Powershell. For that the command is :

```
Start-Process powershell -Verb RunAs -ArgumentList '-NoExit', '-ExecutionPolicy', 'Bypass', '-Command', "iwr -UseBasicParsing -Uri '<URL_TO_FILE> | Invoke-Expression"

```

**Comment by abrichr** [comment]
Thanks @KrishPatel13 ! Please create an issue at https://github.com/openadaptai/web and link back to here.

Other than that, is this PR ready to be merged?

**Comment by KrishPatel13** [comment]
Sure, I will create the Issue there! 

I will be pushing some minor changes to it right now. I will let you know :)

**Comment by KrishPatel13** [comment]
@abrichr Ready to be Merged!

**Review by KrishPatel13 — COMMENTED** [review]
Self-Reviewed!

**Pull request merged**
