### PR TITLE
Investigated Pyment #181

### PR DESCRIPTION
**Pull request by 0dm**
#181 
Ran `pyment -w openadapt` (including nested directories)

Please see the diff, it has added quite a bit, along with some empty docstrings for functions that have no params or return vals.

Are there any particular styles we want?

The current options are:
["javadoc", "reST", "numpydoc", "google"] (default "reST")

### CODE REVIEW

**Comment by 0dm** [comment]
I should add that these docstrings don't really tell us anything new, they're just there..

**Comment by abrichr** [comment]
Interesting, thank you @0dm ! At least it enforces a consistent style. This may be useful if we can't do it with pylint. Related: https://github.com/MLDSAI/OpenAdapt/pull/138

@Mustaballer any thoughts?

**Comment by Mustaballer** [comment]
Sounds good, I think Google style is pretty clean and we can use it going forward

**Comment by 0dm** [comment]
@abrichr Yeah I agree, I didn't really want us to use it anyway - was just looking into it.

**Pull request closed without merging**
