### PR TITLE
Detect diffs via ASCII/OCR

### PR DESCRIPTION
**Pull request by AvidEslami**
Progress towards: #24 
Summary:
Use OCR and ASCII data to determine when an input event has occurred,
         example: task is to open task manager (press cmd, then search for task, then press enter)
                        If cmd window is accidentally closed before search is completed, then the task will repeat and open cmd again. 
                        Once the open cmd window is active, the search will be completed and task manager will be opened.
Implementation:
 - Compares OCR and ASCII data between replay iterations to determine when visual changes occur.

Assumptions:
 - OCR and ASCII data can be used to determine when an input event has occurred (Inputs have visible impact on screen).
 - Screen is not changing due to background processes (e.g. a video is playing in the background).

 TODO:
 - Generate InputEvents from completion results as opposed to previous recordings.
 - Gather OCR and ASCII data of WindowEvents as opposed to entire screen (get_active_window, issue 84).

### CODE REVIEW

**Comment by abrichr** [comment]
Thank @AvidEslami ! 

> Compares OCR and ASCII data between replay iterations to determine when visual changes occur.

Can you please clarify why we want to look at the diff of the OCR/ASCII and not just the screenshot image itself?

**Comment by AvidEslami** [comment]
> Can you please clarify why we want to look at the diff of the OCR/ASCII and not just the screenshot image itself?

Good point @abrichr ,

Since the images are stored using PIL (python imaging library) we can compare them directly, though I found advantages and disadvantages with this implementation.

Advantages of comparing images directly:
 - Captures all visual changes including fine details
 - **If** OCR and ASCII data are **not** needed elsewhere within the application, comparing images directly is more efficient

Advantages of comparing OCR and ASCII data:
 - Less sensitive to minor differences in pixel values (Visual artifacts)
 - **If** OCR and ASCII data are available, less comparisons are required compared to high resolution images (comparing individual pixels)

**Summary:** Using OCR and ASCII data allows us to focus on textual and structural differences while reducing the impact of minor rendering details. For the purposes of OpenAdapt, OCR and ASCII data could additionally be used elsewhere within the task such as when generating completions giving us a potential need to compute them regardless. Therefore using OCR and ASCII data requires less comparisons with reference to using Image data directly, example: 1920x1080 screen resolution (2,073,600 pixel comparisons), vs. 120x30 ASCII + variable OCR size (3600 character comparsions + OCR)

**Comment by abrichr** [comment]
> Therefore using OCR and ASCII data requires less comparisons with reference to using Image data directly, example: 1920x1080 screen resolution (2,073,600 pixel comparisons), vs. 120x30 ASCII + variable OCR size (3600 character comparsions + OCR)

Good point. How does this comparison change if we consider the additional computation required by OCR/ASCII?

**Comment by AvidEslami** [comment]
> Good point. How does this comparison change if we consider the additional computation required by OCR/ASCII?

Here's some Data I was able to gather:

**Case: 1920x1080 screen resolution, 2675 characters on screen**
Average time to compute and compare ascii and OCR: 18.382150602340698
Average time to compare ascii and OCR: 0.002645111083984375
Average time to compare images: 0.024423050880432128
Average time to compute ascii alone: 0.2591431140899658
Average time to compute OCR alone: 18.038353204727173

On my local device, OCR is taking significantly longer than ASCII

**Comment by abrichr** [comment]
It looks like comparing images directly is faster than doing it via ASCII or OCR. Do you agree? If so, should we close this?

**Pull request closed without merging**
