### PR TITLE
Add Installation scripts for complete beginners and/or non-technical users (Implementing #83)

### PR DESCRIPTION
**Pull request by KrishPatel13**
### **Brief Summary:**
This pull request adds two installation scripts (install_puterbot.sh and install_puterbot.ps1) that allow complete beginners and/or non-technical users to easily download and install OpenAdapt on their machines.

### **Approach:**

- My approach was to create two separate installation scripts for Windows and Mac users respectively (install_puterbot.sh and install_puterbot.ps1). 
- The scripts check if Git and Python 3.10 are already installed on the system and if not, they proceed to download and install them. After that, the OpenAdapt repository is cloned, a Python virtual environment is created, and the required packages and libraries are installed. 
- Finally, the database migration is run, and the test suite is executed.

### **Assumptions:**

- The user has internet access.
- The user has administrative privileges on their system.
- The user is running the appropriate script on either macOS or Windows Operating System.

### **Integration of external libraries:**

- I did not integrate any external libraries. This is because, the scripts only require the built-in shell commands of macOS and PowerShell. 
- However, the user needs to use the `curl` command to download the installation script for macOS and the `iwr` (Invoke-WebRequest) command to download the installation script for Windows from the OpenAdaptAI Github repository.

### **Other Comments:**

- For new users who might not be familiar with the technical specifics of installing OpenAdapt, I think these scripts will assist lower the entry barrier.

### CODE REVIEW

**Comment by abrichr** [comment]
Thank you @KrishPatel13 !

It looks like this PR includes changes related to https://github.com/MLDSAI/puterbot/issues/83 (install scripts) and https://github.com/MLDSAI/puterbot/issues/47 (scrubbing).

Can you please split these into separate PRs?

**Comment by KrishPatel13** [comment]
Done!, For this PR, I have removed the unnecessary commits.

**Comment by abrichr** [comment]
Thank you! Can you please push your scrubbing code to a separate PR?

**Comment by KrishPatel13** [comment]
It us not completed yet. That is why I did not make a seprate PR yet. Is that fine ?

**Comment by apgorton** [comment]
@KrishPatel13 that's fine, make a separate PR when it's ready. I think this one can be closed.

**Comment by KrishPatel13** [comment]
I have also made a PR on here: https://github.com/OpenAdaptAI/install/pull/3

**Comment by abrichr** [comment]
Thanks for asking @KrishPatel13 ! What do you think about creating a new PR with the `install` repo as a git submodule? Once that's done we can link back to this and close it.

**Comment by abrichr** [comment]
@KrishPatel13 can you please provide an update on the status of this PR?

**Comment by abrichr** [comment]
@KrishPatel13 can you please prioritize addressing my comments on this PR so that we can get it merged?

**Comment by KrishPatel13** [comment]
Sure!
I just finished the Scrubbing issue and I am lkdging a new PR for it.

As soon as it is done, I will finish up this Issue.

The reason It was on a hault was that there is a change that needs to be made for install scripts.

Now we are using the spacy model

en_core_web_trf.

Anyways, since the scrubbing is now completed. I am going to finish this uo today! :)

**Comment by KrishPatel13** [comment]
Addressed in https://github.com/MLDSAI/OpenAdapt/issues/212

**Pull request closed without merging**
