### PR TITLE
#109 renamed all instances of puterbot to openadapt

### LINKED ISSUE #109: Rename PuterBot to OpenAdapt
This involves renaming all instances of PuterBot to OpenAdapt in code, documentation, and file structure.

### PR DESCRIPTION
**Pull request by 0dm**
# resolved #109
process:
1. cloned the repo and replaced 61 results of "puterbot" with "openadapt" in 21 files
2. renamed "puterbot" directory to "openadapt" and "tests/puterbot" to "tests/openadapt"
3. edited readme instructions
4. ran setup from readme
5. ran pytest ✅
6. recorded a replay ✅
7. visualized ✅
8. NaiveReplay ✅

I'm confident that no instances of puterbot are left - even in hidden files, but please let me know if you do find anything.

### CODE REVIEW

**Comment by 0dm** [comment]
As for "PuterBot", maybe we can turn it into a mascot for openadapt - a helpful little robot 🤖

then when we have a GUI he can act like Clippy 
image

**Review by apgorton — APPROVED** [review]
Looks good. There are some recent changes that need to be merged from MLDSAI:main

**Comment by 0dm** [comment]
merged, looks like it's all ready

**Comment by abrichr** [comment]
Can you please resolve the conflicts?

**Comment by 0dm** [comment]
Should be good.

**Pull request merged**
