### PR TITLE
Implement crop_active_window function

### PR DESCRIPTION
**Pull request by jesicasusanto**
#84 
This pull request implements the crop_active_window function and adds necessary helper functions in record.py and utils.py to support the cropping of the active window from a screenshot.

Changes Made:

In record.py:

Added get_active_window_coordinates_windows() to retrieve the coordinates of the active window on Windows.
Added get_active_window_coordinates_macos() to retrieve the coordinates of the active window on macOS.
Added get_active_window_coordinates_linux() to retrieve the coordinates of the active window on Linux.
Added get_active_window_coordinates() to get the coordinates of the active window based on the current operating system.
Implemented crop_active_window() to crop the active window from a screenshot.
In utils.py:

Updated the crop() function to accept window_coordinates as an argument.
Calculated the width and height of the cropping region based on the provided window coordinates.
Used the mss library to grab the data of the cropped region from the screenshot.

Any feedback is appreciated 🙏🏻thanks!

### CODE REVIEW

**Comment by abrichr** [comment]
Hi @jesicasusanto , thank you for the PR!

It looks like I may not have been clear about the approach. Is there a reason why we don't want to use `WindowEvent.left/top/width/bottom` https://github.com/MLDSAI/OpenAdapt/blob/main/puterbot/models.py#L221 here?

**Comment by jesicasusanto** [comment]
Hi @abrichr ! thanks for giving feedback🙏🏻! I have tried getting the window event by this line of code :

`window_event = get_window_events(get_latest_recording())`

I think that I wasn't able to get the window events within the crop_active_window function because I am trying to access an SQLite object which is the recording object from the main thread. However, crop_active_window is being called in the screen_event_reader thread.

My approach to address this issue is to delete the crop_active_window and directly crop the active window within the read_screen_events function.

This was the error message I got regarding the threading issue :
`  File "c:\users\jesic\pycharmprojects\pat\puterbot\record.py", line 358, in crop_active_window
    window_event = get_window_events(get_latest_recording())    
  File "c:\users\jesic\pycharmprojects\pat\puterbot\crud.py", line 86, in get_latest_recording
    .first()
  File "C:\Users\jesic\PycharmProjects\PAT\puterbot\.venv\lib\site-packages\sqlalchemy\orm\query.py", line 2823, in first       
    return self.limit(1)._iter().first()
  File "C:\Users\jesic\PycharmProjects\PAT\puterbot\.venv\lib\site-packages\sqlalchemy\orm\query.py", line 2915, in _iter       
    result = self.session.execute(
  File "C:\Users\jesic\PycharmProjects\PAT\puterbot\.venv\lib\site-packages\sqlalchemy\orm\session.py", line 1714, in execute   
    result = conn._execute_20(statement, params or {}, execution_options)
  File "C:\Users\jesic\PycharmProjects\PAT\puterbot\.venv\lib\si
te-packages\sqlalchemy\engine\base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "C:\Users\jesic\PycharmProjects\PAT\puterbot\.venv\lib\si
te-packages\sqlalchemy\sql\elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\jesic\PycharmProjects\PAT\puterbot\.venv\lib\si
te-packages\sqlalchemy\engine\base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\jesic\PycharmProjects\PAT\puterbot\.venv\lib\si
te-packages\sqlalchemy\engine\base.py", line 1806, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\jesic\PycharmProjects\PAT\puterbot\.venv\lib\si
te-packages\sqlalchemy\engine\base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "C:\Users\jesic\PycharmProjects\PAT\puterbot\.venv\lib\site-packages\sqlalchemy\util\compat.py", line 208, in raise_     
    raise exception
  File "C:\Users\jesic\PycharmProjects\PAT\puterbot\.venv\lib\si
te-packages\sqlalchemy\engine\base.py", line 1800, in _execute_context
    context = constructor(
  File "C:\Users\jesic\PycharmProjects\PAT\puterbot\.venv\lib\si
te-packages\sqlalchemy\engine\default.py", line 1020, in _init_compiled
    self.cursor = self.create_cursor()
  File "C:\Users\jesic\PycharmProjects\PAT\puterbot\.venv\lib\si
te-packages\sqlalchemy\engine\default.py", line 1391, in create_cursor
    return self.create_default_cursor()
  File "C:\Users\jesic\PycharmProjects\PAT\puterbot\.venv\lib\si
te-packages\sqlalchemy\engine\default.py", line 1394, in create_default_cursor
    return self._dbapi_connection.cursor()
  File "C:\Users\jesic\PycharmProjects\PAT\puterbot\.venv\lib\site-packages\sqlalchemy\pool\base.py", line 1111, in cursor      
    return self.dbapi_connection.cursor(*args, **kwargs)        
sqlalchemy.exc.ProgrammingError: (sqlite3.ProgrammingError) SQLi
te objects created in a thread can only be used in that same thr
ead. The object was created in thread id 18248 and this is thread id 26056.
[SQL: SELECT recording.id AS recording_id, recording.timestamp A
S recording_timestamp, recording.monitor_width AS recording_moni
tor_width, recording.monitor_height AS recording_monitor_height,
 recording.double_click_interval_seconds AS recording_double_cli
ck_interval_seconds, recording.double_click_distance_pixels AS r
ecording_double_click_distance_pixels, recording.platform AS rec
ording_platform, recording.task_description AS recording_task_description
FROM recording ORDER BY recording.timestamp DESC
 LIMIT ? OFFSET ?]
[parameters: [{}]]
(Background on this error at: https://sqlalche.me/e/14/f405) `

**Comment by abrichr** [comment]
Hi @jesicasusanto , to clarify, I don't think we want to modify `record.py` in any way for this. Instead, let's add a `ScreenShot.get_active_window()` that gets the most recent `WindowEvent` before the ScreenShot and uses it to crop the image.

Does that make sense? Please let me know if anything is unclear!

**Comment by jesicasusanto** [comment]
Thank you for your feedback! Yes, that makes sense and I will work on that.

**Comment by jesicasusanto** [comment]
Hi @abrichr 
I have created a `get_active_window` class method. 
I would like to ask clarification on a related matter. When we refer to "cropping" the screenshot, does it mean that we should modify the  Screenshot.take_screenshot()  to capture only the active window?
Please let me know if you have concerns or suggestions. 
Thank you!

**Comment by AvidEslami** [comment]
> I would like to ask clarification on a related matter. When we refer to "cropping" the screenshot, does it mean that we should modify the Screenshot.take_screenshot() to capture only the active window?

Hi Jesica!,
I believe the goal is to continue taking screenshots as normal, but have access to a cropped version of the screenshots to assist with replay strategies.

Motivation: during DemoReplayStrategy we extract all text using OCR, and convert the screenshot to an ASCII representation. It would be more efficient to instead use a cropped version of screenshot and only extract/convert what's necessary.
If this is the case, [this pull request](https://github.com/jesicasusanto/PAT/pull/2), should help with cropping.

Please let me know if I should make any changes or corrections.
Thanks!

**Comment by jesicasusanto** [comment]
Hi @AvidEslami Thank you for your help! I'll test the get_active_window function too.

**Pull request closed without merging**
