### PR TITLE
add pywinauto using poetry

### PR DESCRIPTION
**Pull request by KrishPatel13**
Update `poetry.lock` and `pyproject.toml` to add `pywinauto `library.
**What kind of change does this PR introduce?**
Bugfix: https://github.com/MLDSAI/OpenAdapt/issues/296

**Summary**

**Checklist**
* [x] My code follows the style guidelines of OpenAdapt
* [x] I have performed a self-review of my code
* [x] If applicable, I have added tests to prove my fix is functional/effective
* [x] I have linted my code locally prior to submission
* [x] I have commented my code, particularly in hard-to-understand areas
* [x] I have made corresponding changes to the documentation (e.g. README.md, requirements.txt)
* [x] New and existing unit tests pass locally with my changes

**How can your code be run and tested?**

**Other information**

### CODE REVIEW

**Review by KrishPatel13 — COMMENTED** [review]
Reviewed!

**Comment by 0dm** [comment]
Please add a marker for win32, as this will not work on MacOS.

**Comment by abrichr** [comment]
@KrishPatel13 please prioritize this 🙏

**Review by KrishPatel13 — COMMENTED** [review]
@abrichr Ready for Merging!

**Review by 0dm — APPROVED** [review]

**Pull request merged**
