### PR TITLE
PuterBot-26: Add Guardrails validation to get_completion method in DemoReplayStrategy

### LINKED ISSUE #26: Implement Guardrails
How can we extend DemoReplayStrategy to use https://github.com/ShreyaR/guardrails ?

### PR DESCRIPTION
**Pull request by Mustaballer**
## Overview

- Resolves #26
- Using https://github.com/ShreyaR/guardrails to add a guard for raw LLM output in get_completion method
- Currently use base RAIL file provided in the ^ repo as a start (below)

```<rail version="0.1">
<output>
    <object name="bank_run" format="length: 2">
        <string
            name="explanation"
            description="A paragraph about what a bank run is."
            format="length: 200 280"
            on-fail-length="reask"
        />
        <url
            name="follow_up_url"
            description="A web URL where I can read more about bank runs."
            format="valid-url"
            on-fail-valid-url="filter"
        />
    </object>
</output>

<prompt>
Explain what a bank run is in a tweet.

@xml_prefix_prompt

{output_schema}

@json_suffix_prompt_v2_wo_none
</prompt>
</rail>
```

## Unit Tests Created

- will do after review & iteration

## Steps to QA

- Test to see if current test cases pass, and look for print statements for Success and Fail if end to end testing

## Questions
- What format/structure do we want the output to be after getting the raw LLM output and feeding it to the guardrail?
- Do we want a json output, with any keys or values? Right now it isn't useful since its use a sample RAIL configuration.

### CODE REVIEW

**Comment by atomicrichard** [comment]
Thank you for getting the ball rolling on this @Mustaballer! 🙏 

Ultimately we want to be able to take the output and convert it into a sequence of `InputEvent`s to be replayed. The most direct approach I can think of is to generate a `dict` that can be fed into an `InputEvent` constructor, e.g:

```
llm_completion = ...
input_event_dict = eval(llm_completion)
new_input_event = InputEvent(**input_event_dict)
play_input_event(input_event)
...
```

What do you think? Please let me know if anything is unclear!

**Comment by Mustaballer** [comment]
@atomicrichard To clarify, we want to convert the llm output(llm_completion) which is a string into a single InputEvent object(which can contain child InputEvents like a tree data structure in image below) using the guardrails, and return the parent InputEvent which has links to subsequent InputEvents. Also, I'm wondering what an example of the llm_completion text would look like for our purposes, just to have a clearer idea on how to parse and organize the RAIL configuration.

Thanks :)

image

**Comment by abrichr** [comment]
Great questions!

> To clarify, we want to convert the llm output(llm_completion) which is a string into a single InputEvent object(which can contain child InputEvents like a tree data structure in image below) using the guardrails, and return the parent InputEvent which has links to subsequent InputEvents.

I think ideally we would not want it to contain children, since the children are mostly just there for historical and debugging purposes. Ultimately what we want is a sequence of `InputEvent`s. Whether we get it as a result of a single completion or multiple is unclear. I think we should test both approaches. Perhaps the number of `InputEvent`s per completion should be a configurable parameter.

> Also, I'm wondering what an example of the llm_completion text would look like for our purposes, just to have a clearer idea on how to parse and organize the RAIL configuration.

This is up for debate, but I think a useful starting point (and more robust than my earlier suggestion) is something like a json literal that can be parsed into a Python dict, which can then be passed into the `InputEvent` constructor as keyword arguments. For example:

```
prompt = self.get_prompt()  # TODO
completion = self.get_completion(prompt)  # e.g. "{'name': 'move', 'mouse_x': '1.23, 'mouse_y': '4.56', 'timestamp': '7.89', ...}"
event_dict = json.loads(completion)
input_event = InputEvent(**event_dict)
play_input_event(input_event)
```

(It's not clear to me whether we want to include the timestamp in the completion since we will likely need to override it.)

What do you think?

**Comment by Mustaballer** [comment]
@abrichr Thanks for explaining that! So, if I understand correctly, the intention of using guardrails is to organize the raw LLM output into a JSON structure that represents InputEvents. That makes sense to me. Therefore, I plan to use guardrails to create the JSON structure from the raw LLM output, and then parse the JSON into a dictionary using the method you provided.

Please let me know if this is what you had in mind and if you have any feedback or suggestions. Thank you!

**Comment by abrichr** [comment]
That sounds great as a first step!

Keep in mind we may also want to compress the information somehow, for
example using gists (
https://github.com/MLDSAI/puterbot/issues/27), or some sort of shorthand.
This is to maximize the amount of relevant information we can fit in the
context window.

**Comment by Mustaballer** [comment]
I've been having some trouble using guardrails to structure the llm output. After looking at the logs, I realized that the ocr_text for the Screenshot is quite large and unreadable, and it includes some unrelated text. This could be the reason why I haven't been seeing any changes to the llm output. In the meantime, I created a custom parser function that converts the text into InputEvents based on the output from the prompt(which I changed to be more relevant), and it was successful in playing the input events. 
Input_events

My next steps include writing unit tests for this function. I understand that the purpose of gisting is to compress the prompt. In this case, the screenshot text would get the most relevant info. Is it also important to compress the self.recording_input_events? Finally, my goal is to get the guardrails working to produce more structured output.

**Comment by abrichr** [comment]
Excellent work @Mustaballer !

> My next steps include writing unit tests for this function.

Please do! What should we test?

> I understand that the purpose of gisting is to compress the prompt. In this case, the screenshot text would get the most relevant info. Is it also important to compress the self.recording_input_events?

Exactly right.

> Finally, my goal is to get the guardrails working to produce more structured output.

Can you please clarify? What is next here?

**Comment by Mustaballer** [comment]
@abrichr Thanks for the feedback. I will rebase my changes in main :) rn

**Comment by abrichr** [comment]
Thank you @Mustaballer !

This is what I get when I check out your latest changes and run the DemoReplayStrategy:

```
2023-05-01 15:13:59.200 | WARNING  | puterbot.strategies.llm_mixin:get_completion:44 - Truncating from len(prompt)=124946 to max_input_size=1024
Token indices sequence length is longer than the specified maximum sequence length for this model (47406 > 1024). Running this sequence through the model will result in indexing errors
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/abrichr/MLDSAI/src/puterbot/puterbot/replay.py", line 43, in <module>
    fire.Fire(replay)
  File "/Users/abrichr/MLDSAI/src/puterbot/.venv/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/Users/abrichr/MLDSAI/src/puterbot/.venv/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/Users/abrichr/MLDSAI/src/puterbot/.venv/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/Users/abrichr/MLDSAI/src/puterbot/puterbot/replay.py", line 39, in replay
    strategy.run()
  File "/Users/abrichr/MLDSAI/src/puterbot/puterbot/strategies/base.py", line 47, in run
    input_event = self.get_next_input_event(screenshot)
  File "/Users/abrichr/MLDSAI/src/puterbot/puterbot/strategies/demo.py", line 194, in get_next_input_event
    completion = self.get_completion(self.prompt, max_tokens)
  File "/Users/abrichr/MLDSAI/src/puterbot/puterbot/strategies/llm_mixin.py", line 52, in get_completion
    output_tokens = self.model.generate(
  File "/Users/abrichr/MLDSAI/src/puterbot/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/abrichr/MLDSAI/src/puterbot/.venv/lib/python3.10/site-packages/transformers/generation/utils.py", line 1437, in generate
    return self.greedy_search(
  File "/Users/abrichr/MLDSAI/src/puterbot/.venv/lib/python3.10/site-packages/transformers/generation/utils.py", line 2248, in greedy_search
    outputs = self(
  File "/Users/abrichr/MLDSAI/src/puterbot/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/abrichr/MLDSAI/src/puterbot/.venv/lib/python3.10/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 1075, in forward
    transformer_outputs = self.transformer(
  File "/Users/abrichr/MLDSAI/src/puterbot/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/abrichr/MLDSAI/src/puterbot/.venv/lib/python3.10/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 843, in forward
    position_embeds = self.wpe(position_ids)
  File "/Users/abrichr/MLDSAI/src/puterbot/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/abrichr/MLDSAI/src/puterbot/.venv/lib/python3.10/site-packages/torch/nn/modules/sparse.py", line 162, in forward
    return F.embedding(
  File "/Users/abrichr/MLDSAI/src/puterbot/.venv/lib/python3.10/site-packages/torch/nn/functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self
```

Any ideas?

**Comment by Mustaballer** [comment]
Would you mind trying to run the code again, but this time with a higher value for max_tokens? For instance, you could set it to 300.
`max_tokens = 300 # for example` 
It appears that the problem lies in the fact that we're attempting to encode a sequence that is larger than the maximum sequence length that the model can accommodate. To address this, we can either truncate the sequence or modify the max_length parameter of the tokenizer. In more complex tasks, summarization or using gisting can be beneficial, as you previously mentioned. :)

**Comment by abrichr** [comment]
@Mustaballer thank you for the suggestion!

Please define all constants at the top of the file in UPPER_SNAKE_CASE, e.g.:

```
MAX_TOKENS = 300
RAIL_STR = """
...
"""
...
```

**Comment by abrichr** [comment]
@Mustaballer I implemented the following changes and am still getting the same error:

```
MAX_TOKENS = 300 
...
        max_tokens = MAX_TOKENS
...
        max_tokens = MAX_TOKENS
...
```

**Comment by abrichr** [comment]
@Mustaballer thank you for the great work! Please grab some time on my calendar at your earliest convenience on Weds/Thurs this week: https://www.getclockwise.com/c/richard-abrich/quick-meeting

**Comment by abrichr** [comment]
@Mustaballer I had a bug in my code that I had to fix. Here's the`git diff`:
```
diff --git a/puterbot/strategies/llm_mixin.py b/puterbot/strategies/llm_mixin.py
index d88864e..4e6105a 100644
--- a/puterbot/strategies/llm_mixin.py
+++ b/puterbot/strategies/llm_mixin.py
@@ -44,7 +44,11 @@ class LLMReplayStrategyMixin(BaseReplayStrategy):
             logger.warning(
                 f"Truncating from {len(prompt)=} to {max_input_size=}"
             )
-            prompt = prompt[max_input_size:]
+            prompt = prompt[-max_input_size:]
+            logger.warning(
+                f"Truncated {len(prompt)=}"
+            )
+
         logger.debug(f"{prompt=} {max_tokens=}")
         input_tokens = self.tokenizer(prompt, return_tensors="pt")
         pad_token_id = self.tokenizer.eos_token_id
```
`python -m puterbot.replay DemoReplayStrategy`:

```
2023-05-02 02:36:49.530 | WARNING  | puterbot.strategies.llm_mixin:get_completion:44 - Truncating from len(prompt)=124946 to max_input_size=1024
2023-05-02 02:36:49.530 | WARNING  | puterbot.strategies.llm_mixin:get_completion:48 - Truncated len(prompt)=1024
2023-05-02 02:36:52.325 | INFO     | puterbot.strategies.demo:get_next_input_event:195 - completion="~~~\n\n{ 'key' : 'key', 'value' : 'key', 'value' : 'value', 'value' : 'value', 'value' : 'value', 'value' : 'value', 'value' : 'value', 'value' : 'value', 'value' : 'value', 'value' : 'value', 'value' : 'value', 'value' : 'value', 'value' : 'value', 'value' :"
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/abrichr/MLDSAI/src/puterbot/puterbot/replay.py", line 43, in <module>
    fire.Fire(replay)
  File "/Users/abrichr/MLDSAI/src/puterbot/.venv/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/Users/abrichr/MLDSAI/src/puterbot/.venv/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/Users/abrichr/MLDSAI/src/puterbot/.venv/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/Users/abrichr/MLDSAI/src/puterbot/puterbot/replay.py", line 39, in replay
    strategy.run()
  File "/Users/abrichr/MLDSAI/src/puterbot/puterbot/strategies/base.py", line 47, in run
    input_event = self.get_next_input_event(screenshot)
  File "/Users/abrichr/MLDSAI/src/puterbot/puterbot/strategies/demo.py", line 197, in get_next_input_event
    parsed_events = self.parse_input_event(completion)
  File "/Users/abrichr/MLDSAI/src/puterbot/puterbot/strategies/demo.py", line 99, in parse_input_event
    s = completion[1].replace(", ", "").replace(",", "").replace("'", "")
IndexError: list index out of range
```
Have you gotten this to run? Can you please provide the output of `git status`? Thank you! 🙏

**Comment by Mustaballer** [comment]
This is what I get when I do git status:
image

The completion that is generated starts with `"~~~\n\n{ 'key' : 'key', 'value' : 'key', 'value' : 'value', 'value, ..."`
whereas on my end it shows this as the completion.
image

I think one of the reasons could be because of the fact that the prompt itself is getting truncated a lot, where it might not get to the actual instruction, which is 
image

To address this issue, I plan to improve the parser function to handle various string inputs and avoid throwing errors. Additionally, I will investigate gisting to preserve context data.

**Comment by abrichr** [comment]
@Mustaballer any update on this?

**Comment by Mustaballer** [comment]
I had temporarily paused work on this project, but I now plan to conduct additional testing with guardrails. My focus will be on enforcing strict standards for the language model completions. While I will be using the current models initially, I believe there is potential for guardrails to be employed in other replay strategies as well. I will provide a retrospective update on my progress and determine whether it is appropriate to close the project based on the results.

**Comment by Mustaballer** [comment]
Closing the pull request because I was unable to achieve the desired outcome while utilizing the "guardrails" library for rigorous parsing of Action Events.

**Pull request closed without merging**
