### PR TITLE
Implement MarketPlace Web App

### PR DESCRIPTION
**Pull request by jesicasusanto**
This pull request implements the Marketplace web App.
Recreate front-end based on UI Mock Up
Work on data logic

UI MockUp using Figma :

238046146-9fca8c72-5a89-4a3c-b0b1-7569fc1c9d91
238046114-1cb772a3-1fd6-41dd-af9a-d726719ef670

Thank you!

steps to reproduce assuming node.js is installed :
pip install cookiecutter
cookiecutter https://github.com/tiangolo/full-stack-fastapi-postgresql
npm run serve #to run server

### CODE REVIEW

**Comment by abrichr** [comment]
Thanks @jesicasusanto ! It looks like the link you posted is broken, can you please fix it?

**Comment by abrichr** [comment]
Here are screenshots of the Figma:

image

image

Please include screenshots on future PRs where applicable 🙏 

Looking forward to digging into this next week!

**Comment by jesicasusanto** [comment]
Hi @abrichr , I am currently in the process of setting up the web app with [https://github.com/tiangolo/full-stack-fastapi-postgresql](url).

However, I am unsure about the values I should provide for each input variable listed in the repository (excluding the ones that require generating a random 32-character hexadecimal string using OpenSSL). Could you please guide me on this? Thank you!

**Comment by jesicasusanto** [comment]
I moved the PR to the new marketplace repo [https://github.com/OpenAdaptAI/marketplace/pull/1](url)

**Comment by abrichr** [comment]
Thank you @jesicasusanto ! Can you please fix the link in your last comment?

**Pull request closed without merging**
