### PR TITLE
Minigpt-4 #12

### PR DESCRIPTION
**Pull request by angelala3252**
This pull request implements a new strategy called ```minigpt4.py``` that generates the next InputEvent by taking in a task description, then passing MiniGPT-4 this description, the past InputEvents, and the screenshot, and asking it to generate the next event. I also used OCR to generate a description of the screenshot to give to MiniGPT4 as well. I used a similar approach to the PR for issue #15 but used MiniGPT-4 instead.

Issues/Uncertainties:

- Wasn’t sure where to put the imported MiniGPT-4 module in the puterbot repository
- Also had to rename the MiniGPT-4 since it had a hyphen in its name, so it couldn't be imported
- Unsure if necessary to reinitialize MiniGPT-4 each time as it could take more time than needed

TODO:

- convert MiniGPT-4's returned text into an InputEvent rather than just a text action
- create unit tests

ChatGPT transcript: https://drive.google.com/file/d/1_6tlxgyYSZj6snCxuaQV52arbG2rK026/view?usp=share_link

Any feedback is appreciated!

### CODE REVIEW

**Comment by abrichr** [comment]
Thank you @angelala3252 !

Please follow the instructions at https://github.com/MLDSAI/puterbot/pull/56#issuecomment-1530755076 but modified for your fork, e.g.:

```
git remote add angelala3252 https://github.com/angelala3252/puterbot.git
git fetch angelala3252
# what goes here to run your code? please create a branch update your PR to merge from that branch, e.g.:
git checkout feat/<your-feature-name>  # please fill this in
pip install -r requirements.txt  # please fill this in
python -m ...  # please fill this in

**Comment by abrichr** [comment]
@angelala3252 thank you for the great work! Please grab some time on my calendar at your earliest convenience on Weds/Thurs this week: https://www.getclockwise.com/c/richard-abrich/quick-meeting

**Comment by abrichr** [comment]
@angelala3252 I would love to try this out but I can't get it to work:
```
(.venv) abrichr@MacBook-Pro-2 puterbot % python -m puterbot.replay GPTReplayStrategy
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/abrichr/MLDSAI/src/puterbot/puterbot/replay.py", line 4, in <module>
    from crud import get_latest_recording
ModuleNotFoundError: No module named 'crud'
```
Can you please run:
```
git fetch
git checkout origin/master -- puterbot/config.py
git checkout origin/master -- puterbot/crud.py
git checkout origin/master -- puterbot/db.py
git checkout origin/master -- puterbot/events.py
git checkout origin/master -- puterbot/models.py
git checkout origin/master -- puterbot/record.py
git checkout origin/master -- puterbot/replay.py
git checkout origin/master -- puterbot/strategies/__init__.py
cat "from puterbotlstrategies.minigpt4 import GPTReplayStrategy" >> puterbot/strategies/__init__.py
git checkout origin/master -- puterbot/utils.py
git checkout origin/master -- puterbot/visualize.py
```
This will replace your unnecessary and unrelated changes and keep the relevant ones.

Please commit the result and push your latest. Also please modify the branch of this PR to point to your feature branch. Also rename your feature branch so that it isn't literally feat/my-feature but something descriptive like `feat/minigpt4`: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request

**Comment by abrichr** [comment]
After implementing the above on my machine I get:

```
(.venv) abrichr@MacBook-Pro-2 puterbot % python -m puterbot.replay GPTReplayStrategy
2023-05-02 02:20:20.671 | INFO     | __main__:replay:19 - strategy_name='GPTReplayStrategy'
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/abrichr/MLDSAI/src/puterbot/puterbot/replay.py", line 43, in <module>
    fire.Fire(replay)
  File "/Users/abrichr/MLDSAI/src/puterbot/.venv/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/Users/abrichr/MLDSAI/src/puterbot/.venv/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/Users/abrichr/MLDSAI/src/puterbot/.venv/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/Users/abrichr/MLDSAI/src/puterbot/puterbot/replay.py", line 21, in replay
    strategy_class_by_name = get_strategy_class_by_name()
  File "/Users/abrichr/MLDSAI/src/puterbot/puterbot/utils.py", line 375, in get_strategy_class_by_name
    from puterbot.strategies import BaseReplayStrategy
  File "/Users/abrichr/MLDSAI/src/puterbot/puterbot/strategies/__init__.py", line 5, in <module>
    from puterbot.strategies.minigpt4 import GPTReplayStrategy
  File "/Users/abrichr/MLDSAI/src/puterbot/puterbot/strategies/minigpt4.py", line 20, in <module>
    from MiniGPT4.minigpt4.common.config import Config
ModuleNotFoundError: No module named 'MiniGPT4'
```

@angelala3252 Can you please add to `requirements.txt`? You can do a `pip freeze > requirements.txt`

**Comment by angelala3252** [comment]
@abrichr After looking into the MiniGPT-4 repo a bit further, I realized that I missed some steps in the setup and that in order to fully initialize MiniGPT-4, we would have to request access to download the LLaMA weights here https://docs.google.com/forms/d/e/1FAIpQLSfqNECQnMkycAp2jP4Z9TFX0cGR4uf7b_fBxjY_OjhJILlKGA/viewform

How do you want me to proceed?

**Comment by angelala3252** [comment]
This is the code that would be used to run my code (but as I mentioned above I can't actually run my solution because of the issue with the MiniGPT-4 installation and weights):

`git remote add angelala3252 https://github.com/angelala3252/puterbot.git
git fetch angelala3252
git checkout feat/minigpt4
pip install -r requirements.txt
python -m puterbot.replay NaiveReplayStrategy # assuming you have a replay you want to playback`

I've updated the requirements.txt file to include the packages that the MiniGPT-4 repo requires (as it uses a conda environment rather than a requirements.txt file) in a [new PR](https://github.com/MLDSAI/PuterBot/pull/81) that merges from my feat/minigpt4 branch instead of my main branch.

**Comment by abrichr** [comment]
Thanks @angelala3252!

> in order to fully initialize MiniGPT-4, we would have to request access
to download the LLaMA weights here
https://docs.google.com/forms/d/e/1FAIpQLSfqNECQnMkycAp2jP4Z9TFX0cGR4uf7b_fBxjY_OjhJILlKGA/viewform

Ideally this would all be automated. The user should be able to follow the
setup instructions in a brand new PuterBot installation, and have
everything just work out of the box. Do you mind taking this on? 🙏

**Comment by abrichr** [comment]
@angelala3252 should we close this in favor of your other PR https://github.com/MLDSAI/puterbot/pull/81 ?

**Pull request closed without merging**
