### PR TITLE
#103 : Rename InputEvent(s) to ActionEvent(s)

### LINKED ISSUE #103: Refactor: InputEvent -> Action
This involves replacing:

InputEvent -> Action
input_event -> action

What else? Please provide links in the comments (including to documentation)

### PR DESCRIPTION
**Pull request by 0dm**
(copied from issue)

replaced "input_events" with "actions" : 73 occurrences in 8 files
replaced "input_event" with "action" : 78 occurrences in 11 files (ignore alembic)
replaced "InputEvent" with "Action" : 25 occurrences in 11 files
added alembic revision

- recording ✅
- visualize ✅
- replay ✅
- pytests ✅

realized I forgot to actually make the PR lol

### CODE REVIEW

**Review by apgorton — COMMENTED** [review]
Looks good. There are a few other instances, my comment lists a couple but not all. Please do a grep and look for any others. There may be some comments or cases where it's fine to leave 'input' but we want to be fairly consistent to avoid any confusion. Please be a bit more descriptive with PR titles, it doesn't have to be long.

**Comment by abrichr** [comment]
Thank you @0dm ! Can you please modify the PR title to something more descriptive?

**Comment by 0dm** [comment]
Not quite, I pushed it back because it would interfere with other branches a bit (would require many of them to merge / resolve conflicts) and I'd like to take some time to make sure everything looks consistent. But the current code is fully functional, so if you'd like to merge it now (and further edit later) then there's no issues.

**Review by abrichr — APPROVED** [review]
LGTM!

**Pull request merged**
